### ISSUE TITLE
Traefik in docker X-Real-Ip check

### ISSUE THREAD

**Issue by jmattheis** [screego/server#10]
https://www.reddit.com/r/selfhosted/comments/j60eng/screego_multi_user_screen_sharing_via_browser/g7xwzf2/?utm_source=reddit&utm_medium=web2x&context=3

Maybe, there should be a setting for disabling the ip whitelisting.

**Comment by Nevermole** [comment]
@jmattheis Have you actually manage to have _screego_ running behind _traefik_?

**Comment by jmattheis** [comment]
No not yet.

**Comment by mmguero** [comment]
I have run it behind traefik, but only where the two machines (sharing the screen and viewing the screen share) are on the local network so I don't think it's flexed the traversal stuff really. I'll try more configurations if i can.

**Comment by mmguero** [comment]
Seems like all I can get is some variation of:

```
Creating network "screego_default" with the default driver
Creating screego_screego_1 ... done
Attaching to screego_screego_1
screego_1  | 2020-10-08T21:09:32Z DBG Logger initialized
screego_1  | 2020-10-08T21:09:32Z INF Loaded Users amount=2
screego_1  | 2020-10-08T21:09:32Z INF Start TURN/STUN addr=0.0.0.0:3478
screego_1  | 2020-10-08T21:09:32Z INF Start HTTP addr=0.0.0.0:5050
screego_1  | 2020-10-08T21:09:44Z DBG WebSocket Close code=1000 reason="room with id amused-bronze-donkey does not exist"
screego_1  | 2020-10-08T21:09:44Z DBG WebSocket error="read tcp 172.23.23.2:5050->172.23.23.1:39786: use of closed network connection" type=read
screego_1  | 2020-10-08T21:10:52Z DBG TURN strict ip check failed allowedIp=172.23.23.1:42931 connectingIp=96.18.88.33
screego_1  | turn ERROR: 2020/10/08 21:10:52 error when handling datagram: failed to handle Allocate-request from 172.23.23.1:42931: no user exists for btvo0n4lviqc1vqheb0gclient
```

That particular log is with traefik running on host networking mode. I'm going to try it on a bridged network just for the heck of it.

**Comment by mmguero** [comment]
With traefik acting on a bridged network like I usually do, and then screego on that same network, I get this:

```
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:18:47Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
screego_1  | 2020-10-08T21:19:03Z DBG TURN authenticated addr=172.23.24.1:59493 realm=screego
```

But my wife at home who's helping me test this only sees a blank gray screen with the room name at the top and the controls at the bottom, not the screen share, which is the same thing she saw with traefik network_mode:host.

Here are my configs:

docker-compose.yml for traefik:

```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=user@example.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    networks:
      - proxy
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  proxy:
    external:
      name: traefik-proxy
```

screego docker-compose file:

```
version: "3.7"

services:
  screego:
    image: screego/server:1.0.1
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 5050
    ports:
      - 0.0.0.0:3478:3478
      - 0.0.0.0:3478:3478/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screego.rule=Host(`screen.example.org`)"
      - "traefik.http.routers.screego.entrypoints=websecure"
      - "traefik.http.routers.screego.tls.certresolver=myresolver"
      - "traefik.http.services.screego.loadbalancer.server.port=5050"
    volumes:
      - ./htpasswd:/etc/screego.passwd:ro
    environment:
      SCREEGO_EXTERNAL_IP: "17.5.7.8"
      SCREEGO_SECRET: "xxxxxxxxxxxx"
      SCREEGO_SERVER_ADDRESS: "0.0.0.0:5050"
      SCREEGO_TURN_ADDRESS: "0.0.0.0:3478"
      SCREEGO_TRUST_PROXY_HEADERS: "true"
      SCREEGO_AUTH_MODE: "turn"
      SCREEGO_CORS_ALLOWED_ORIGINS: "https://screen.example.org"
      SCREEGO_USERS_FILE: "/etc/screego.passwd"
      SCREEGO_LOG_LEVEL: debug

networks:
  proxy:
    external:
      name: traefik-proxy
```
