### ISSUE TITLE
screego on cloudflare tunnels?

### ISSUE THREAD

**Issue by ashishjullia** [screego/server#167]
I'm trying to run on cloudflare tunnels but for some reason unable to share the screen.

The app is up and running but the screen share part does nothing, is there a special setting required?

I'm using the follow `docker-compose.yml`:

```yaml
version: "3.7"
services:
  screego:
    image: ghcr.io/screego/server:1.10.0
    ports:
      - 5050:5050
      - 3478:3478
      - 50000-50200:50000-50200/udp
    environment:
      SCREEGO_EXTERNAL_IP: "dns:screego.mydomainname.com@1.1.1.1:53"
      SCREEGO_TURN_PORT_RANGE: "50200:50400"
      SCREEGO_CORS_ALLOWED_ORIGINS: "https://screego.mydomainname.com"
      SCREEGO_AUTH_MODE: none
      SCREEGO_TRUST_PROXY_HEADERS: "false"
  cf-tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<TOKEN>
```

I'm able to get the web app up and running but the screen sharing part is not working.
