### ISSUE TITLE
Docker + TURN not working

### ISSUE THREAD

**Issue by mbleichner** [screego/server#27]
In our company, direct traffic between PCs is blocked, so we have to use the built-in TURN server.

This works fine when I'm using the binary, but not with the docker image (same configuration).

When inspecting port 3478 with tcpdump, it seems like some (not all) UDP packets use an internal docker IP address, which looks a bit suspicious to me.

```
  screego:
    image: screego/server:1.0.1
    ports:
      - mode: host
        target: 5050
        published: 5050
      - mode: host
        protocol: tcp
        target: 3478
        published: 3478
      - mode: host
        protocol: udp
        target: 3478
        published: 3478
    environment:
      - SCREEGO_EXTERNAL_IP=X.X.151.230
      - SCREEGO_SERVER_ADDRESS=0.0.0.0:5050
      - SCREEGO_TURN_ADDRESS=0.0.0.0:3478
      - SCREEGO_AUTH_MODE=none
      - SCREEGO_SERVER_TLS=true
      - SCREEGO_TLS_CERT_FILE=/etc/letsencrypt/live/xxx/fullchain.pem
      - SCREEGO_TLS_KEY_FILE=/etc/letsencrypt/live/xxx/privkey.pem
      - SCREEGO_LOG_LEVEL=debug
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
```
