### ISSUE TITLE
Could not start presentation. (mediaDevices undefined) Are you using https?

### ISSUE THREAD

**Issue by othin87** [screego/server#78]
Hi all, i've a question, i've start mi istance of screengo with a docker-compose, this the yml:
```
version: "3.7"
services:
  screego:
    image: screego/server:1.2.0
    ports:
      - 5050:5050
      - 3478:3478
      - 50000-50100:50000-50100/udp
    environment:
      SCREEGO_TURN_PORT_RANGE: "50000:50100"
      SCREEGO_EXTERNAL_IP: "MYIP"
      SCREEGO_TURN_STRICT_AUTH: "false"
```
all ok, when i log in http://myip:5050 and i see the correct page, but when i create a room and i try to share my screen, appear this error:
![Schermata da 2021-02-28 17-10-31](https://user-images.githubusercontent.com/64959793/109425380-42802500-79e8-11eb-8cc0-9f3b45b8e038.png)
i don't undestand why...
Thanks all
