### ISSUE TITLE
Create volume in docker

### ISSUE THREAD

**Issue by karpaz** [screego/server#94]
Hi,
Iam using docker, and my screego run in container.
We are using self-signed TLS cert. We need to store our cert in container, which path we should choose in container ?
Also we need to keep screego.config in docker. 
I hope that your answer help other people too.
Thx

**Comment by jmattheis** [comment]
Hi, you can choose any path, because you need to define the path inside the configuration. Here's a docker-compose.yml that uses a self-signed cert:
```yaml
version: "3.7"
services:
  screego:
    image: screego/server:1.4.0
    network_mode: host
    volumes:
      - ./example.crt:/example.crt
      - ./example.key:/example.key
    environment:
      SCREEGO_EXTERNAL_IP: "192.168.178.2"
      SCREEGO_SERVER_TLS: "true"
      SCREEGO_TLS_CERT_FILE: /example.crt
      SCREEGO_TLS_KEY_FILE: /example.key
```

When using docker you don't have to use a config file, you can use environment variables instead.
